lua/mason-lspconfig/server_configurations/groovyls/init.lua

Expected list instead of string.

Fix groovy-ls launch

---

lua/mason-lspconfig/lspconfig_hook.lua

feat: better feedback when auto installing servers

---

lua/mason-lspconfig/lspconfig_hook.lua
tests/mason-lspconfig/setup_spec.lua
tests/minimal_init.vim

- test: add test cases for merging configs
- fix: let user_config take precedence when merging config tables

fix: let user_config take precedence when merging config tables

---

lua/mason-lspconfig/win-exepath-compat.lua

https://github.com/williamboman/mason.nvim/discussions/411

fix(r_language_server): expand exepath on Windows

---

lua/mason-lspconfig/server_configurations/angularls/init.lua

fix(angularls): fix windows detection

---

lua/mason-lspconfig/server_configurations/astro/init.lua
lua/mason-lspconfig/typescript.lua

feat(astro): use vendored tsdk if workspace tsdk not available

---

lua/mason-lspconfig/server_configurations/astro/init.lua
lua/mason-lspconfig/server_configurations/volar/init.lua
lua/mason-lspconfig/typescript.lua

fix(volar): provide tsdk location rather than full tsserver path

---

doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua
lua/mason-lspconfig/win-exepath-compat.lua

Add mappings for the nil language server for nix

feat: add nil

---

lua/mason-lspconfig/api/command.lua

Closes williamboman/mason.nvim#751.

refactor(api): directly call into :MasonInstall and :MasonUninstall Lua APIs

---

lua/mason-lspconfig/server_configurations/pylsp/init.lua

Closes williamboman/mason.nvim#822.

feat(pylsp): add python-lsp-ruff

---

lua/mason-lspconfig/lspconfig_hook.lua

refactor: use reduce to merge config tables

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add standardrb

---

lua/mason-lspconfig/server_configurations/julials/init.lua

Run `:MasonUpdate` and `:MasonInstall julia-lsp`.

fix(julials)!: compat with new registry

---

lua/mason-lspconfig/api/command.lua
lua/mason-lspconfig/ensure_installed.lua
lua/mason-lspconfig/init.lua
lua/mason-lspconfig/install.lua
lua/mason-lspconfig/notify.lua
lua/mason-lspconfig/server_configurations/pylsp/init.lua
tests/mason-lspconfig/setup_spec.lua

feat: notify if mason has not been set up

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add typst_lsp mapping

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add ols (Odin Language Server) mapping

---

doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add rubocop (#251)

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add matlab_ls

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add pkgbuild_language_server

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua
scripts/lua/mason-scripts/mason-lspconfig/generate.lua

Hi, here is a draft pull request to add [mdx-analyzer](https://github.com/mdx-js/mdx-analyzer) support. :purple_heart: 
See also:
- https://github.com/neovim/nvim-lspconfig/pull/2784
- https://mason-registry.dev/registry/list#mdx-analyzer

feat: add mdx-analyzer support

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add thriftls (#275)

---

doc/mason-lspconfig.txt

docs(vimcdocs): improve setup_handlers section example

---

lua/mason-lspconfig/server_configurations/apex_ls/init.lua

This will require reinstallation of the package in order to link the jar: https://github.com/mason-org/mason-registry/pull/2916

fix(apex_ls): fix jar location

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

PR for nvim-lspconfig
https://github.com/neovim/nvim-lspconfig/pull/2973
Already available in mason-registry:
https://github.com/mason-org/mason-registry/blob/main/packages/bzl/package.yaml

feat: add bzl mapping

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

https://github.com/mason-org/mason-registry/pull/4895

add jinja-lsp

---

doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

also: we might want to deprecate swift-mesonlsp

feat: add mesonlsp

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

feat: add `regols` support

---

lua/mason-lspconfig/lspconfig_hook.lua

Fix deprecation warning on newest nightly

fix: prefer vim.islist over vim.tbl_islist

---

README.md
doc/mason-lspconfig-mapping.txt
doc/server-mapping.md
lua/mason-lspconfig/mappings/filetype.lua
lua/mason-lspconfig/mappings/server.lua

because this PR is now merged https://github.com/neovim/nvim-lspconfig/pull/3294
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#kcl
i would like to add support to KCL in mason

feat(kcl): add kcl support
