williamboman/mason-lspconfig.nvim

lua/mason-lspconfig/ensure_installed.lua, lua/mason-lspconfig/init.lua, lua/mason-lspconfig/lspconfig_hook.lua
Reduces the modules required by mason-lspconfig when calling .setup() by
~27, to a total of 30 (YMMV). There are potentially more optimizations
to be done elsewhere, but it's negligible at this point (also,
impatient.nvim is a thing).
=> feat: lazily require modules on ad-hoc basis

lua/mason-lspconfig/api/command.lua, lua/mason-lspconfig/init.lua
- extract the logic from the `available_server_completion` into a dedicated function that is re-usable
```lua
require("mason-lspconfig").get_available_servers()
```
- use `get_installed_servers` to remove duplicate logic in `installed_server_completion`
=> feat: add get_available_servers

doc/mason-lspconfig.txt, lua/mason-lspconfig/init.lua, tests/mason-lspconfig/api/api_spec.lua
Allow `get_available_servers` to accept a query filter
The available keys are
- filetype (string): Only return servers with matching fileyupe
related: https://github.com/williamboman/mason.nvim/issues/86
```lua
local all_servers = get_available_servers()
local js_servers = get_available_servers({ ft = "javascript" })
```
=> feat: get_available_servers now accepts a filter

lua/mason-lspconfig/server_configurations/julials/init.lua
This is done partly for convenience reasons, but also to better guard
against breaking changes in the future (the executable itself holds more
installation-specific information now, as opposed to this function).
Fixes #30.
=> fix(julials)!: change cmd to use new Mason-linked executable

lua/mason-lspconfig/server_configurations/volar/init.lua
Volar introduced some breaking changes in version 1.0 https://github.com/johnsoncodehk/volar/pull/1916. Not sure if I did everything properly, but volar works for me with these changes.
Also see https://github.com/neovim/nvim-lspconfig/pull/2181
Thank you for your work!
=> fix: support volar 1.0

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
This PR adds support for Red Hat's [Drools Rule Language](https://docs.drools.org/latest/drools-docs/docs-website/drools/language-reference/index.html#con-drl_drl-rules) (ft=`drools`, ext=`.drl`). The [drools-lsp](https://github.com/kiegroup/drools-lsp/) server config was recently merged into [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) (also written by me). The generated doc link in nvim-lspconfig is [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#drools_lsp).
The companion PR in mason.nvim is [here](https://github.com/williamboman/mason.nvim/pull/898).
_Thank you so much!_
Signed-off-by: David Ward <dward@redhat.com>
=> feat: add drools_lsp

lua/mason-lspconfig/server_configurations/drools_lsp/init.lua
fix(drools-lsp): apply mason's package install path of the jar on behalf of the user
Signed-off-by: David Ward <dward@redhat.com>
=> fix(drools-lsp): apply mason's package install path of the jar on behalf of the user

lua/mason-lspconfig/server_configurations/solang/init.lua
This will be the new location of LLVM-patched bins once https://github.com/mason-org/mason-registry/ is live.
=> feat(solang): also include $MASON/opt/solang llvm bins

lua/mason-lspconfig/init.lua, lua/mason-lspconfig/lspconfig_hook.lua, tests/mason-lspconfig/setup_spec.lua
You should be able to run headless commands without mason-lspconfig starting installations in the background with
limited ability to wait until they're done.
=> fix: don't auto install servers when headless

lua/mason-lspconfig/init.lua, tests/helpers/lua/test_helpers.lua, tests/mason-lspconfig/setup_spec.lua, vim.yml
Implements usage of `register_aliases` added in this PR: https://github.com/williamboman/mason.nvim/pull/1146
=> feat: register package aliases

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
https://github.com/neovim/nvim-lspconfig/pull/2493
https://github.com/mason-org/mason-registry/pull/1015
Should make this work:
```
mason_lspconfig.setup {
ensure_installed = {"azure_pipelines_ls"},
}
```
=> feat: add azure_pipelines_ls to the server mapping

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
From these change
* https://github.com/neovim/nvim-lspconfig/pull/2558
* https://github.com/mason-org/mason-registry/pull/1160
This PR updates the server mapping for `helm-ls`  supported
=> add: helm-ls autoconfig

lua/mason-lspconfig/init.lua, lua/mason-lspconfig/lspconfig_hook.lua, tests/mason-lspconfig/setup_spec.lua
Many users probably set these up in the wrong order but experience no impact on functionality. These may think the notification is a breaking change when it's not, so the trade-off here is to only notify when we know it impacts functionality.
=> refactor: only notify bad setup order if it impacts functionality

lua/mason-lspconfig/api/command.lua, lua/mason-lspconfig/mappings/language.lua
This module was removed from mason, didn't realize it was being used elsewhere.
=> fix: fix language map

lua/mason-lspconfig/server_configurations/astro/init.lua
This refactor was part of `@astrojs/language-server@2.0.0`.
See https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/astro.lua
Fixes https://github.com/withastro/language-tools/issues/559
=> fix(astro): `typescript.serverPath` -> `typescript.tsdk`

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
jq-lsp support was added in williamboman/mason.nvim#793
this pr adds missing mapping for it
=> feat: add jq-lsp mapping

lua/mason-lspconfig/server_configurations/rescriptls/init.lua
Config override is not needed and it points to the old binary name which breaks LSP usage with lspconfig. This fixes rescript language server.
=> Delete rescript config.

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
Gleam should not be installed through Mason. See https://github.com/mason-org/mason-registry/pull/3872.
=> fix: remove gleam

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
Adds server mapping for [vacuum](https://github.com/daveshanley/vacuum), which recently added lsp support and is already available in the [mason-registry](https://github.com/mason-org/mason-registry/blob/main/packages/vacuum/package.yaml).
The PR in [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/pull/3065) has been merged and is using the same name.
=> feat: add vacuum language server

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
Fennel-ls is already in the mason [registry] and in [lspconfig].
This PR links the two together.
[registry]: https://github.com/mason-org/mason-registry/pull/4648
[lspconfig]: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/fennel_ls.lua
=> feat: add fennel-ls

README.md, doc/mason-lspconfig-mapping.txt, doc/server-mapping.md, lua/mason-lspconfig/mappings/filetype.lua, lua/mason-lspconfig/mappings/server.lua
`ruff` now has a built in language server, which `nvim-lspconfig` already has support for.
=> Add new ruff server

lua/mason-lspconfig/server_configurations/astro/init.lua, lua/mason-lspconfig/server_configurations/pylsp/init.lua, lua/mason-lspconfig/server_configurations/volar/init.lua
Some modules don't need to be eagerly loaded at the config time. With this patch, when using pylsp, the following modules are no longer loaded at startup, which saves about 0.6ms on my desktop. 
* mason-core.result
* mason-core.receipt
* mason-core.process
* mason-core.spawn
* mason-core.installer.context
* mason-core.async.control
* mason-core.installer.linker
* mason-core.installer
* mason-core.providers
* mason-core.managers.pip3
=> perf: lazy-require some modules during config
